name: citysense
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - shapely>=2.1.2
  - geopandas>=1.1.2
  - pyproj>=3.7.1
  - rasterio>=1.4.3
  - numpy>=2.2.0
  - pandas>=2.3.0
  - pip
  - pip:
    - -e ".[dev]"
